### ISSUE TITLE
Specify shapely version

### ISSUE THREAD

**Issue by mathcass** [philiptromans/mapswipe-ml-dataset-generator#1]
I looks like this is using the `shapely` package for some geo operations. What version are you using? 

One method for communicating versions to collaborators is via a [`requirements.txt`](https://pip.readthedocs.io/en/1.1/requirements.html) file.

**Comment by philiptromans** [comment]
Hi @mathcass does #2 look good to you?

**Comment by mathcass** [comment]
@philiptromans Yep! That solves it!
